# Generated by Django 3.1.5 on 2021-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210126_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeMogel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
